# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/eacdd863-62a9-4951-a5af-4990ba45397c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A111-AB3B";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # MIGRATION TODO (fw-fanctrl): the live dotfiles hardware file sets
  # `hardware.fw-fanctrl`, but that option's module is not present in nix-meta's
  # input set (the dotfiles pull it from the fw-fanctrl flake / nixos-hardware
  # framework module — provenance unconfirmed). Left commented so the framework
  # config evaluates; restore by adding the fw-fanctrl input to nix-meta and
  # importing its nixosModule, then re-enable this block verbatim.
  #
  # hardware.fw-fanctrl = {
  #   enable = true;
  #   config = {
  #     defaultStrategy = "lazy";
  #     strategyOnDischarging = "custom";
  #     strategies = {
  #       "custom" = {
  #         fanSpeedUpdateFrequency = 5;
  #         movingAverageInterval = 40;
  #         speedCurve = [
  #           { temp = 45; speed = 0; }
  #           { temp = 65; speed = 15; }
  #           { temp = 70; speed = 25; }
  #           { temp = 85; speed = 35; }
  #         ];
  #       };
  #     };
  #   };
  # };
}